<?php

/**
 * @file
 * Contains reservation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reservation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reservation module.
    case 'help.page.reservation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('module of booking university rooms') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function reservation_theme() {
  return [
    'reservation' => [
      'render element' => 'children',
    ],
  ];
}
